import os

COUNTY_MAP = {
        'adair': 'https://results.enr.clarityelections.com//KY/Adair/106381/270022/reports/detailtxt.zip',
        'allen': 'https://results.enr.clarityelections.com//KY/Allen/106382/269929/reports/detailtxt.zip',
        'anderson': 'https://results.enr.clarityelections.com//KY/Anderson/106383/269814/reports/detailtxt.zip',
        'ballard':'https://results.enr.clarityelections.com//KY/Ballard/106384/269644/reports/detailtxt.zip',
        'barren':'https://results.enr.clarityelections.com//KY/Barren/106385/270006/reports/detailtxt.zip',
        'bath':'',
        'bell':'',
        'boone':'https://results.enr.clarityelections.com//KY/Boone/106388/269882/reports/detailtxt.zip',
        'bourbon':'https://results.enr.clarityelections.com//KY/Bourbon/106389/269873/reports/detailtxt.zip',
        'boyd':'',
        'boyle':'https://results.enr.clarityelections.com//KY/Boyle/106391/269901/reports/detailtxt.zip',
        'braken':'https://results.enr.clarityelections.com//KY/Boyle/106391/269901/reports/detailtxt.zip',
        'breathitt':'',
        'brekinridge':'https://results.enr.clarityelections.com//KY/Breckinridge/106394/270298/reports/detailtxt.zip',
        'bullitt':'https://results.enr.clarityelections.com//KY/Bullitt/106395/270068/reports/detailtxt.zip',
        'butler':'https://results.enr.clarityelections.com//KY/Butler/106396/269674/reports/detailtxt.zip',
        'caldwell':'',
        'calloway':'https://results.enr.clarityelections.com//KY/Calloway/106398/270004/reports/detailtxt.zip',
        'campbell':'https://results.enr.clarityelections.com//KY/Campbell/106399/269825/reports/detailtxt.zip',
        'carlisle':'https://results.enr.clarityelections.com//KY/Carlisle/106400/266368/reports/detailtxt.zip',
        'carroll':'',
        'carter':'https://results.enr.clarityelections.com//KY/Carter/106402/269899/reports/detailtxt.zip',
        'casey':'https://results.enr.clarityelections.com//KY/Casey/106403/266169/reports/detailtxt.zip',
        'christian':'https://results.enr.clarityelections.com//KY/Christian/106404/269905/reports/detailtxt.zip',
        'clark':'https://results.enr.clarityelections.com//KY/Wayne/106496/269628/reports/detailtxt.zip',
        'clay':'',
        'clinton':'',
        'crittenden':'https://results.enr.clarityelections.com//KY/Crittenden/106408/269924/reports/detailtxt.zip',
        'cumberland':'https://results.enr.clarityelections.com//KY/Cumberland/106409/269919/reports/detailtxt.zip',
        'daviess':'',
        'edmonson':'https://results.enr.clarityelections.com//KY/Edmonson/106411/269660/reports/detailtxt.zip',
        'elliott':'',
        'estill':'https://results.enr.clarityelections.com//KY/Estill/106413/269744/reports/detailtxt.zip',
        'fayette':'https://results.enr.clarityelections.com//KY/Fayette/106414/269666/reports/detailtxt.zip',
        'fleming':'https://results.enr.clarityelections.com//KY/Fleming/106415/269870/reports/detailtxt.zip',
        'floyd':'',
        'franklin':'https://results.enr.clarityelections.com//KY/Fulton/106418/269898/reports/detailtxt.zip',
        'fulton':'https://results.enr.clarityelections.com//KY/Fulton/106418/269898/reports/detailtxt.zip',
        'gallatin':'',
        'garrard':'https://results.enr.clarityelections.com//KY/Garrard/106420/269775/reports/detailtxt.zip',
        'grant':'',
        'graves':'https://results.enr.clarityelections.com//KY/Graves/106422/269810/reports/detailtxt.zip',
        'grayson':'https://results.enr.clarityelections.com//KY/Grayson/106423/269827/reports/detailtxt.zip',
        'green':'',
        'greenup':'https://results.enr.clarityelections.com//KY/Greenup/106425/269888/reports/detailtxt.zip',
        'hancock':'https://results.enr.clarityelections.com//KY/Hancock/106426/269707/reports/detailtxt.zip',
        'hardin':'',
        'harlan':'https://results.enr.clarityelections.com//KY/Harlan/106428/269863/reports/detailtxt.zip',
        'harrison':'',
        'hart':'https://results.enr.clarityelections.com//KY/Hart/106430/269602/reports/detailtxt.zip',
        'henderson':'',
        'henry':'https://results.enr.clarityelections.com//KY/Henry/106432/269867/reports/detailtxt.zip',
        'hickman':'https://results.enr.clarityelections.com//KY/Hickman/106433/269860/reports/detailtxt.zip',
        'hopkins':'',
        'jackson':'',
        'jefferson':'',
        'jessamine':'https://results.enr.clarityelections.com//KY/Jessamine/106437/269851/reports/detailtxt.zip',
        'johnson':'',
        'kenton':'',
        'knott':'',
        'knox':'',
        'larue':'',
        'laruel':'',
        'lawrence':'https://results.enr.clarityelections.com//KY/Lawrence/106444/269834/reports/detailtxt.zip',
        'lee':'',
        'leslie':'',
        'letcher':'',
        'lewis':'',
        'lincoln':'',
        'livingston':'https://results.enr.clarityelections.com//KY/Livingston/106450/269816/reports/detailtxt.zip',
        'logan':'https://results.enr.clarityelections.com//KY/Logan/106451/269733/reports/detailtxt.zip',
        'lyon':'',
        'madison':'',
        'magoffin':'',
        'marion':'',
        'marshall':'https://results.enr.clarityelections.com//KY/Marshall/106456/269832/reports/detailtxt.zip',
        'martin':'',
        'mason':'https://results.enr.clarityelections.com//KY/Mason/106458/269833/reports/detailtxt.zip',
        'mccraken':'https://results.enr.clarityelections.com//KY/McCracken/106459/269914/reports/detailtxt.zip',
        'mccreary':'',
        'mcLean':'https://results.enr.clarityelections.com//KY/McLean/106461/269739/reports/detailtxt.zip',
        'meade':'https://results.enr.clarityelections.com//KY/Meade/106462/269877/reports/detailtxt.zip',
        'menifee':'',
        'mercer':'https://results.enr.clarityelections.com//KY/Mercer/106464/269958/reports/detailtxt.zip',
        'metcalfe':'https://results.enr.clarityelections.com//KY/Metcalfe/106465/269859/reports/detailtxt.zip',
        'monroe':'https://results.enr.clarityelections.com//KY/Monroe/106466/269891/reports/detailtxt.zip',
        'montgomery':'https://results.enr.clarityelections.com//KY/Montgomery/106467/269823/reports/detailtxt.zip',
        'morgan':'',
        'muhlenberg':'https://results.enr.clarityelections.com//KY/Muhlenberg/106469/269945/reports/detailtxt.zip',
        'nelson':'',
        'nicholas':'https://results.enr.clarityelections.com//KY/Nicholas/106471/269758/reports/detailtxt.zip',
        'ohio':'',
        'oldham':'https://results.enr.clarityelections.com//KY/Oldham/106473/269831/reports/detailtxt.zip',
        'owen':'',
        'owsley':'https://results.enr.clarityelections.com//KY/Owsley/106475/270047/reports/detailtxt.zip',
        'pendleton':'',
        'perry':'',
        'pike':'https://results.enr.clarityelections.com//KY/Pike/106478/269936/reports/detailtxt.zip',
        'powell':'',
        'pulsaki':'https://results.enr.clarityelections.com//KY/Pulaski/106480/269791/reports/detailtxt.zip',
        'robertson':'https://results.enr.clarityelections.com//KY/Robertson/106481/269839/reports/detailtxt.zip',
        'rockcastle':'',
        'rowan':'',
        'russell':'https://results.enr.clarityelections.com//KY/Russell/106484/265995/reports/detailtxt.zip',
        'scott':'',
        'shelby':'',
        'simpson':'',
        'spencer':'https://results.enr.clarityelections.com//KY/Spencer/106488/269911/reports/detailtxt.zip',
        'taylor':'https://results.enr.clarityelections.com//KY/Taylor/106489/269889/reports/detailtxt.zip',
        'todd':'',
        'trigg':'https://results.enr.clarityelections.com//KY/Trigg/106491/269998/reports/detailtxt.zip',
        'trimble':'',
        'union':'https://results.enr.clarityelections.com//KY/Union/106493/270002/reports/detailtxt.zip',
        'warren':'https://results.enr.clarityelections.com//KY/Washington/106495/269980/reports/detailtxt.zip',
        'webster':'https://results.enr.clarityelections.com//KY/Webster/106497/269627/reports/detailtxt.zip',
        'wayne':'https://results.enr.clarityelections.com//KY/Wayne/106496/269628/reports/detailtxt.zip',
        'whitley':'https://results.enr.clarityelections.com//KY/Whitley/106498/269939/reports/detailtxt.zip',
        'wolfe':'',
        'woodford':'',
             }

RAW_DIR = '/edata/KY/raw'
os.chdir(RAW_DIR)
# loop thru links and put them in the dir
for (cty, url) in COUNTY_MAP.items():
    if not url:
        continue
    os.system('curl {} -o {}/{}.zip'.format(url, RAW_DIR, cty))
    cmd = 'unzip {}/{}.zip'.format(RAW_DIR, cty)
    print(cmd)
    os.system(cmd)
    cmd = 'mv detail.txt {}.txt'.format(cty)
    print(cmd)
    os.system(cmd) 

